Addition of the Work and About myself section for my portfolio
wdavidcch/portfolio pull request #2
Opened 2022-05-27 17:11 UTC by wdavidcch

This pull request is to add the new parts to my portfolio on the project on day 4 for microverse.
The new parts are the Works section for works that I have done and the skills part to show the knowledge and experience I have.

2022-05-27 20:56 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @wdavidcch 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 

## Required Changes :recycle: :recycle:
- [ ] Kindly make sure to improve the design of your portfolio by correctly using the correct values provided at [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A988) like:
   - Margin bottom of the **about me** section
   - And other comments pointed below
- [ ] To make your README looks perfect with the required template for every project in Microverse, I suggest you correct the typo in its extension name. `README.md` instead of `README.me`.
- [ ] Kindly improve your PR description to make it more explicit about all the details/changes you made in this milestone. I suggest you add on it a list of the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#:~:text=Project%20requirements,enable%2C%20hover%2C%20etc.).) as they are changes you completed in the milestone
- [ ] **Check the comments under the review**.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 20:56 UTC, tresorsawasawa commented on index.html
> +    </article>
- [x] For kindly make sure all the containers of the **about me** section are wrapped in a `<section>` tag for goos semantics and Html best practice.

2022-05-27 20:56 UTC, tresorsawasawa commented on index.html
> +    </article>
- [x] Kindly make sure that you use the `<section>` tag to wrap all the cards container as required for the project and for good HTML semantics. Remember to change both open and close tags.

2022-05-27 20:56 UTC, tresorsawasawa commented on assets/css/style.css
> +
- [x] Kindly make sure the **Get My Resume** `button` follow the button styling: `Active`, `Hover`, and `Pressed` (see the design). Take a look below and check the correct colors from the Figma design:
![buttons](https://user-images.githubusercontent.com/83042742/170768440-ad55a3ee-3757-49e4-8580-3f89b8074e68.png)

2022-05-27 20:56 UTC, tresorsawasawa commented on index.html
> +                <p>Languages</p>
- [x] For HTML good semantics kindly use the `h` tag as this is a sub-title and not a paragraph. I can be **h2, h3, or h4**.

2022-05-27 20:56 UTC, tresorsawasawa commented on index.html
> +                <p>Frameworks</p>
- [x] For HTML good semantics kindly use the `h` tag as this is a sub-title and not a paragraph. I can be **h2, h3 or h4**.

2022-05-27 20:56 UTC, tresorsawasawa commented on index.html
> +                <p>Skills</p>
- [x] For HTML good semantics kindly use the `h` tag as this is a sub-title and not a paragraphh. I can be **h2, h3 or h4**.

2022-05-27 20:56 UTC, tresorsawasawa commented on index.html
> +    </article>
- [x] Kindly make sure the technology categories ("Languages", "Frameworks" and "Skills") are in a `<ul>` tag, each of them in a `<li>`. And this `<ul>`  should be a part of **About section** not aoutside.

2022-05-27 20:56 UTC, tresorsawasawa commented on assets/css/style.css
> +  font-size: var(--md);
- [ ] Kindly make sure the **Get My Resume** `button` follow the button styling: `Active`, `Hover`, and `Pressed` (see the design). Take a look at the previous pic where I pointed out the other button and check the correct colors from the Figma design.

2022-05-27 20:56 UTC, tresorsawasawa commented on assets/css/style.css
> +}
- [ ] Kindly make sure the about me description has the some `font-family`, `font-style`, `font-size`, `line-height`, and `color` as the one from [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A988)

2022-05-27 20:56 UTC, tresorsawasawa commented on assets/css/style.css
> +
- [ ] Make sure to add the correct used color from the Figma template design.

2022-05-27 21:01 UTC, wdavidcch commented on index.html
> +    </article>
Hey I have to change the divs tag for section tags? or the article tag for section tag? @tresorsawasawa

2022-05-27 21:07 UTC, wdavidcch commented on index.html
> +    </article>
are you talking about for example in line 139 change <div class="product-card> for <section class="product-card> @tresorsawasawa

2022-05-27 21:42 UTC, wdavidcch commented on index.html
> +    </article>
Thank you... Can you be more specific I did not understand well what I have to change

2022-05-27 21:42 UTC, wdavidcch commented on index.html
> +    </article>
@tresorsawasawa

2022-05-28 01:59 UTC, wdavidcch commented on index.html
> +    </article>
Hey, be aware that I'm not in the st template so using a ul for the categories ("Languages", "Frameworks" and "Skills") maybe could not be the best way to do it in my template cuz they are separated like as cards. I'm in template 3.

If that is mandatory It's okay but please let me know before doing the new PR. @tresorsawasawa

2022-05-28 02:47 UTC, Lucas-Masaba approved these changes
# Hello @wdavidcch 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Linter checks passed ✔️ 
- Made most changes requested by previous reviewer 👍 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

[OPTIONAL]
- You added a few pseudo-classes required for actions on the buttons. Please add all of them as required by the Figma template.  As of now, when I hover over a button I see no change.  Follow this guide as seen below 
![image](https://user-images.githubusercontent.com/45460192/170806875-01b51c28-0d54-43be-bbbc-873b56f7647e.png)

2022-05-28 12:56 UTC, wdavidcch commented
Hey @Lucas-Masaba I noticed that but the hover is actually working, you can see it if you try with another color. What is happening here is that the color in the enable and in the hover is the same and we can not see the difference. Look it here...

enabled color: #36B37F
hover color: #36B37F

![Screenshot from 2022-05-28 08-54-27](https://user-images.githubusercontent.com/102382778/170826498-1b6febae-5369-4a72-a24d-a829ed6ae0ce.png)
![Screenshot from 2022-05-28 08-54-13](https://user-images.githubusercontent.com/102382778/170826502-048ab752-6710-4f8d-88a9-86e0b2e418e5.png)

2022-05-28 12:57 UTC, merged