Desktop version (Responsive Design)
wdavidcch/portfolio pull request #4
Opened 2022-06-01 22:04 UTC by wdavidcch

In this project, I used media queries in the CSS file to make my Desktop version look like the template I selected from Figma (3rd one) 
The media queries start to work with the min-width: 768px or wider.

In order to lay out the elements on the page, I used Grid and Flexbox. I did my best to replicate as much as possible with the original design --> [the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

2022-06-01 22:56 UTC, tufoinnkuo10 requested changes
Hi @wdavidcch 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
![almost](https://media.giphy.com/media/WOTMeqMcNkLuXibbKz/giphy.gif)
Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-01 22:56 UTC, tufoinnkuo10 commented on index.html
>      <footer>
- [ ] please kindly reduce the space between your skill section cards 
your design 
![Screenshot (97)_LI](https://user-images.githubusercontent.com/65298048/171514301-e11b3d44-5f56-43e1-98fc-52915010e3bb.jpg)
figma design
![Screenshot (99)](https://user-images.githubusercontent.com/65298048/171514323-e4fed5e6-413d-444d-a4a5-c72fafe57cad.png)

2022-06-01 22:56 UTC, tufoinnkuo10 commented on index.html
> -        </form>
- [ ] kindly add a little bit of padding to your desktop form placeholders so the get the position of the original figma version

2022-06-01 22:56 UTC, tufoinnkuo10 commented on index.html
>              <ul>
- [ ] please add a medium social icon. it will be of help when you start writing your articles

2022-06-02 16:02 UTC, Kandy-Peter approved these changes
Hi @wdavidcch,

# APPROVED 🟢 

Great implementation of all the requirements in this milestone. 👏

Your web app looks really fantastic. 🎉 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

#### CONGRATULATIONS! 🎉 

##  Optional suggestion

- [x] Please, ensure that you include an explanation, a "why", for each requested change.

# CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 16:02 UTC, Kandy-Peter commented on assets/css/style.css
> +  padding-left: 0;
- [x] OPTIONAL: I would suggest you make your cards more responsive and improve your design quality. You can take a look at the code below:
```
.desktop ul {
   display:grid;
   grid-template-column: repeat(auto-fit, minmax(350px, 1fr);
}
```

2022-06-02 16:26 UTC, wdavidcch commented on assets/css/style.css
> +  padding-left: 0;
Okay thank you

2022-06-02 16:27 UTC, merged